services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: complexpassword
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: